'use strict';
const fullName = 'Tré Mitchell';
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const isCool = true;
console.log('value of isCool:', isCool);
console.log('typeof isCool:', typeof isCool);
const totalPets = 0;
console.log('value of totalPets:', totalPets);
console.log('typeof totalPets:', typeof totalPets);
const empty = null;
console.log('value of null:', empty);
console.log('typeof empty:', typeof empty);
let nothing;
console.log('value of nothing:', nothing);
console.log('typeof nothing:', typeof nothing);
